port: 465 # ssl
timeout: 5 # seconds
year_before_repeat: 5 # years

smtp_server: "smtpauths.bluewin.ch"
mail_sender: "louis.munier@bluewin.ch"

test_config:
  input_file: "input_mail_list.yaml"
  output_file: "output_mail_list.yaml"

  mail_subject: "Test"
  mail_body: |
      CFG_RECIPIENT - This is a test over multiple lines :
      CFG_TARGET
      Results coming later on!
