# Config - For testing purposes
# ------------
# This file contains all the configuration parameters for the mail sender.
# Also the different files to get or save the mail lists and results.
port: 465 # ssl
smtp_server: "smtp.test.com"
mail_sender: "test@test.com"

test_config:
  input_file: "input_mail_list.yaml"
  output_file: "output_mail_list.yaml"

  mail_subject: "Test"
  mail_body: |
      CFG_RECIPIENT - This is a test over multiple lines :
      CFG_TARGET
      Results coming later on!
